Default			= "По умолчанию"
Yes			 	= "Да"
No				= "Нет"
or				= "или"
Next			= "Следующий"
Previous		= "Предыдущий"
Forward			= "Вперед"
Back			= "Назад"
Stop			= "Стоп"
Cancel			= "Отменить"
Save			= "Сохранить"
Continue		= "Продолжить"
Open			= "Открыть"
Close			= "Закрыть"
Delete			= "Удалить"
Remove			= "Убрать"
Show			= "Показать"
Hide			= "Скрыть"
Add				= "Добавить"

January			= "Январь"
February		= "Февраль"
March			= "Март"
April			= "Апрель"
May				= "Май"
June			= "Июнь"
Jule			= "Июль"
August			= "Август"
September		= "Сентябрь"
October			= "Октябрь"
November		= "Ноябрь"
December		= "Декабрь"

Monday			= "Понедельник"
Tuesday			= "Вторник"
Wednesday		= "Среда"
Thursday		= "Четверг"
Friday			= "Пятница"
Saturday		= "Суббота"
Sunday			= "Воскресенье"

Spring			= "Весна"
Summer			= "Лето"
Autumn			= "Осень"
Winter			= "Зима"

Today			= "Сегодня"
Yesterday		= "Вчера"
Tomorrow		= "Завтра"

Week			= "Неделя"
Month			= "Месяц"
Year		 	= "Год"
Day				= "День"
Hour			= "Час"
Minute			= "Минута"
Second			= "Секунда"

ago				= " назад"

weeks			= " недель"
monthes			= " месяцев"
years			= " лет"
days			= " дней"
minutes			= " минут"
seconds			= " секунд"









