

_title			= "Регистрация"


_register			= "Регистрация"
_your_name			= "Ваше имя"
_your_surname		= "Ваша фамилия"
_your_login			= "Логин"
_your_email			= "Электронная почта"
_password			= "Пароль"
_repeat_password	= "Ещё раз пароль"

_register_in		= "Зарегистрироваться"
_clear_form			= "Очистить"


_error_reg_emp		= "Проверьте форму на ошибки"
_error_reg_not_email = "Разве это E-Mail?"
_error_reg_exists = "Пользователь с таким логином или почтой уже есть!<br />Вы забыли пароль?"